### ISSUE TITLE
Map `Type.typeOfResource` in CSV importer

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#157] opened 2018-09-13 16:23 UTC
Given a CSV with a `Type.typeOfResource` column:

 - [x] importing this CSV creates objects with the values in the `resource_type` attribute.

**Comment by val99erie** [comment] 2018-09-14 14:11
This is a duplicate of both #47 and #95.

**Closed** 2018-09-19 13:10 UTC
Labels: in progress, ingest, metadata
