### ISSUE TITLE
Add CSV mapping for Type.typeOfResource

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#95] opened 2018-09-05 16:37 UTC
Map `Type.typeOfResource` during CSV import:

Given a CSV with a `Type.typeOfResource` column:

  - [ ] importing this CSV creates objects with the values in the `resource_type` attribute.

**Comment by val99erie** [comment] 2018-09-12 19:00
This story seems to be a duplicate of #47.  I'll close it as duplicate.

**Closed by val99erie** 2018-09-12 19:00 UTC
Labels: backlog
