### ISSUE TITLE
Add terms to californica SHOW view

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#206] opened 2018-09-19 16:47 UTC
**STORY**
As a librarian / archivist / metadata professional, I would like to see all of the descriptive metadata associated with an object, so that I can verify it's correctness.

**ACCEPTANCE**
Ensure each of the following fields appears on a single item show page:
 - [ ] Title
 - [ ] Subject
 - [ ] Type of Resource
 - [ ] Copyright Status
 - [ ] Name (subject)
 - [ ] Location
 - [ ] Repository
 - [ ] Publisher
 - [ ] Rights (country of origin)
 - [ ] Rights Holder
 - [ ] Date
 - [ ] Local Identifier
 - [ ] Title
 - [ ] Date Created
 - [ ] Extent
 - [ ] Medium
 - [ ] Dimensions
 - [ ] Description
 - [ ] Funding Note
 - [ ] Longitude
 - [ ] Latitude
 - [ ] Caption
 - [ ] Language

reference (CSV Mappings)[https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=875035976]

**Comment by little9** [comment] 2018-09-20 15:43
Dupe of #195

**Closed** 2018-09-20 15:43 UTC
Labels: design, discovery, metadata, review
